<!-- http://localhost:8080/ -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Simple PHP Website</title>
</head>
<body>
    <h1 class="text-gray-900">Welcome to My Simple PHP Website</h1>
    <?php
        echo "<p>This content is generated by PHP!</p>";
    ?>
</body>
</html>

